const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{DatabaseSync}=require('node:sqlite');
(async()=>{
  const {createApi}=await import('../cloud/api.mjs');const database=new DatabaseSync(':memory:');
  database.exec(fs.readFileSync(path.join(__dirname,'../cloud/schema.sql'),'utf8'));
  const DB={prepare(sql){return {bind(...args){const stmt=database.prepare(sql);return {all:async()=>({results:stmt.all(...args)}),run:async()=>stmt.run(...args)};}};}};
  const handle=createApi({maps:[{id:'tan_vien'}],quests:[{stage:20,title:'Rèn vũ khí'}]});
  const call=(token,path,method='GET',body)=>handle(new Request('https://leon-project.pages.dev'+path,{method,headers:token?{Authorization:'Bearer '+token,'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined}),{DB});
  const a='a'.repeat(64),b='b'.repeat(64);
  assert.equal((await call(null,'/api/choice-memory')).status,401);
  const entry={at:'2026-10-03T07:00:00Z',reason:'choice_result',dialog:'Đại Phu',key:'daily',label:'Nhận Việc Này',outcome:'success',value:4,character:'A',quest:{stage:20}};
  assert.equal((await call(a,'/api/quest-failures','POST',entry)).status,200);
  await call(a,'/api/quest-failures','POST',entry);
  const am=await (await call(a,'/api/choice-memory')).json(),bm=await (await call(b,'/api/choice-memory')).json();
  assert.equal(am.length,2,'Maps and one deduplicated personal event');assert.equal(bm.length,1,'Other user only sees public maps');
  const q=await (await call(a,'/api/quest-line')).json();assert.equal(q.quests[0].events.length,1);
  await call(a,'/api/quest-line','POST',{stage:20,status:'fixed',note:'Done'});
  assert.equal((await (await call(b,'/api/quest-line')).json()).fixes[20],undefined);
  assert.equal((await (await call(a,'/api/quest-line')).json()).fixes[20].status,'fixed');
  const ai=await (await call(a,'/api/ai/plan','POST',{key:'daily',options:['Nhận Việc Này']})).json();assert.equal(ai.source,'memory');
  assert.equal((await call(a,'/api/accounts','POST',{accounts:[{password:'do not save'}]})).status,501);
  await call(b,'/api/quest-failures','POST',{...entry,reason:'watchdog',outcome:'fail',character:'B'});
  const adminHandle=createApi({quests:[{stage:20,title:'Rèn vũ khí'}],signingSecret:'test-secret',adminOnlyQuestLine:true,adminKeyHash:require('node:crypto').createHash('sha256').update('test-admin-key').digest('hex')});
  const adminCall=(path,adminToken,method='GET',body)=>adminHandle(new Request('https://example.org'+path,{method,headers:{Authorization:'Bearer '+a,'X-Leon-Admin':adminToken||'','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),{DB});
  assert.equal((await adminCall('/api/quest-line')).status,403);
  assert.equal((await adminCall('/api/quest-line',null,'POST',{stage:20,status:'verified',note:'unauthorized'})).status,403);
  const auth=await (await adminCall('/api/admin/auth',null,'POST',{key:'test-admin-key'})).json();
  assert.equal((await adminCall('/api/quest-line',auth.token)).status,403,'Normal session cannot impersonate admin');
  const aggregate=await (await adminCall('/api/quest-line',auth.adminToken)).json();assert.equal(aggregate.quests[0].events.length,2);assert.equal(aggregate.fixes[20],undefined,'Global fixes separate from personal fixes');
  await adminCall('/api/quest-line',auth.adminToken,'POST',{stage:20,status:'fixed',note:'Global repair'});
  assert.equal((await (await adminCall('/api/quest-line',auth.adminToken)).json()).fixes[20].note,'Global repair');
  database.close();console.log('Cloud D1 schema, owner isolation, deduplication, quest fixes and memory regressions passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
