const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
let now=1000, listener;
const window={PNTT:{Gateway:{selfId:'me',socket:{addEventListener(type,fn){listener=fn;}}}}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../extension/session-metrics.js'),'utf8'),{window,Date:{now:()=>now}});
const metrics=window.__tienloMetrics;
metrics.start({exp:100,stones:50,realmId:'r1'});
listener({data:JSON.stringify({op:'kill',by:'other',id:'a'})});
listener({data:JSON.stringify({op:'kill',by:'me',id:'b'})});
listener({data:'invalid'});
now+=60000;
let result=metrics.read({exp:110,stones:55,realmId:'r1'},200);
assert.equal(result.kills,1);assert.equal(result.xpPerHour,600);assert.equal(result.killsPerHour,60);
metrics.read({exp:0,stones:45,realmId:'r2'},300);
result=metrics.read({exp:15,stones:47,realmId:'r2'},300);
assert.equal(result.xpGained,25);assert.equal(result.stonesGained,7);assert.equal(result.stonesSpent,10);
metrics.stop({exp:15,stones:47,realmId:'r2'});
now+=60000;
listener({data:JSON.stringify({op:'kill',by:'me',id:'c'})});
result=metrics.read({exp:20,stones:100,realmId:'r2'},300);
assert.equal(result.seconds,60);assert.equal(result.kills,1);assert.equal(result.xpGained,25);
console.log('Session metrics regressions passed');
